## Compose file to run everything locally.
## Not usable in production. NOT SECURE.


version: "2"
services:
  database:
    build: ./database
    container_name: GGJ2020-db-service
    ports: 
      - "5432:5432"
  #  environment:
  #    - POSTGRES_USER=user
  #    - POSTGRES_PASSWORD=example
  #    - POSTGRES_DB=sampledb
  backend: 
    build: ./backend
    container_name: GGJ2020-api-service
    environment:
      # Override the database.
      - DATABASE_HOST=jdbc:postgresql://database/sampledb
      - PLAY_SECRET=adfadsfdsfa
    ports:
      - "9001:9000"
    depends_on:
      - database
  frontend:
    # The angular app. Which is dependend on the backend.
    build: ./frontend
    container_name: GGJ2020-frontend-service
    ports:
      - "8080:80"
    depends_on:
      - backend
