version: "2"
services:
  database:
    build: ./database
    container_name: formfiller-db-service
    ports: 
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=demodb
  backend: 
    build: ./backend
    container_name: formfiller-api-service
    environment:
      # Override the database.
      - DATABASE_HOST=jdbc:mysql://database/TEST
      - PLAY_SECRET=adfadsfdsfa
    ports:
      - "9001:9000"
    depends_on:
      - database
  frontend:
    # The angular app. Which is dependend on the backend.
    build: ./frontend
    container_name: formfiller-frontend-service
    ports:
      - "8080:80"
    depends_on:
      - backend
