## Compose file to run everything locally.
## Not usable in production. NOT SECURE.
version: "2"
services:
  backend: 
    build: ./backend
    container_name: GGJ2020-api-service
    environment:
      - PLAY_SECRET=adfadsfdsfa
  frontend:
    # NGINX that serves the 
    build: ./frontend
    container_name: GGJ2020-frontend-service
    ports:
      - "8080:80"
    depends_on:
      - backend
